In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest,chi2,RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('Pima.csv',index_col=0)

In [6]:
df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [7]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [8]:
test=SelectKBest(score_func=chi2,k=5)
chi=test.fit(x,y)

In [9]:
chi.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [10]:
x.columns

Index(['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], dtype='object')

In [11]:
chidf=pd.DataFrame(chi.scores_).T
chidf.columns=x.columns

In [12]:
chidf

preg         plas       pres      skin         test        mass  \
0  111.519691  1411.887041  17.605373  53.10804  2175.565273  127.669343   

       pedi         age  
0  5.392682  181.303689

# RFE

In [15]:
lg=LogisticRegression()

rfe=RFE(lg,n_features_to_select=5)

rfe.fit(x,y)

RFE(estimator=LogisticRegression(), n_features_to_select=5)

In [16]:
rfe.ranking_

array([1, 1, 2, 3, 4, 1, 1, 1])

In [17]:
rfe.support_

array([ True,  True, False, False, False,  True,  True,  True])

In [19]:
rfe_df=pd.DataFrame(rfe.ranking_).T
rfe_df.columns=x.columns
rfe_df

preg  plas  pres  skin  test  mass  pedi  age
0     1     1     2     3     4     1     1    1

# Tree Based approach

In [24]:
dt=DecisionTreeClassifier(criterion='entropy')

In [25]:
dt.fit(x,y)

DecisionTreeClassifier(criterion='entropy')

In [27]:
dt_df=pd.DataFrame(dt.feature_importances_).T
dt_df.columns=x.columns
dt_df

preg      plas      pres      skin      test      mass      pedi  \
0  0.093713  0.232947  0.091396  0.043071  0.030394  0.248503  0.115165   

       age  
0  0.14481

 -Univariate Selection
     -Test,Plasma,Age,Mass
     
     
    -RFE:
       -preg,ples,mass,pdi,age
       
       
     -Tree:
        -Plasma,Mass,Pedi,Age

# Cross Validation

In [37]:
from sklearn.model_selection import KFold,LeaveOneOut,cross_val_score

In [38]:
kf = KFold(n_splits=10,random_state=1, shuffle=True)
score = cross_val_score(LogisticRegression(),x,y,cv=kf)

In [39]:
score.mean()

0.7720608339029391

In [41]:
#Leave one out

In [43]:
df.shape

AttributeError: 'DecisionTreeClassifier' object has no attribute 'shape'

In [44]:
le = LeaveOneOut()
le_score = cross_val_score(LogisticRegression(),x,y,cv = le)

In [35]:
le_score

array([1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [36]:
le_score.mean()

0.7786458333333334